// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTest.Data;

#nullable disable

namespace WebTest.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("WebTest.Entity.MsJenis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MsJenis");
                });

            modelBuilder.Entity("WebTest.Entity.TrKasir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Diskon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipeCostumer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBayar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBelanja")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TsCrt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrKasir");
                });
#pragma warning restore 612, 618
        }
    }
}
